### ISSUE TITLE
Running demo fails

### ISSUE THREAD

**Issue by DanielRTRD** [hfurubotten/enturclient#8]
```
AA-C0D8E-010:EnTur dsbilling$ python EnTurClientTest.py 
Traceback (most recent call last):
  File "EnTurClientTest.py", line 1, in <module>
    from enturclient import EnturPublicTransportData
  File "/Library/Python/2.7/site-packages/enturclient/__init__.py", line 1, in <module>
    from enturclient.api import EnturPublicTransportData
  File "/Library/Python/2.7/site-packages/enturclient/api.py", line 21
    client_name: str,
               ^
SyntaxError: invalid syntax
AA-C0D8E-010:EnTur dsbilling$ 
```

Any suggestions?

**Comment by hfurubotten** [comment]
Looks like you are running on python version 2.7? 
I have built in type annotations in the client, which (if I remember correctly) is a version 3.5+ feature. Can you try out a newer python version? Hopefully it will function better there.

**Comment by DanielRTRD** [comment]
I am not able too, current systems require Python 2.7, so everything needs to support that version, hehe :)
